export const designKits = [
  {
    id: "blue_collar_pro",
    name: "Blue Collar Pro",
    description: "Contractors, electricians, HVAC, plumbing, roofing.",
    industry_architecture: "service",
    color_theme: "industrial",
    layout_preset: "split_screen",
    primary_color: "#0b2a5b",
    secondary_color: "#f5b400",
    tertiary_color: "#f7f4ef",
  },
  {
    id: "hospitality",
    name: "Hospitality",
    description: "Restaurants, bars, cafes, food trucks, venues.",
    industry_architecture: "restaurant",
    color_theme: "modern",
    layout_preset: "featured_media",
    primary_color: "#7c2d12",
    secondary_color: "#f59e0b",
    tertiary_color: "#fff7ed",
  },
  {
    id: "industrial_ops",
    name: "Industrial Ops",
    description: "Manufacturing, mills, plants, field operations.",
    industry_architecture: "industrial",
    color_theme: "industrial",
    layout_preset: "asymmetrical",
    primary_color: "#111827",
    secondary_color: "#f97316",
    tertiary_color: "#f3f4f6",
  },
  {
    id: "executive",
    name: "Executive",
    description: "Law firms, consultants, accountants, professional services.",
    industry_architecture: "professional",
    color_theme: "classic",
    layout_preset: "centered",
    primary_color: "#1f2937",
    secondary_color: "#b45309",
    tertiary_color: "#fafaf9",
  },
  {
    id: "tech_data",
    name: "Tech / Data",
    description: "SaaS, analytics, dashboards, AI, automation.",
    industry_architecture: "data_management",
    color_theme: "dark",
    layout_preset: "showcase",
    primary_color: "#2563eb",
    secondary_color: "#22d3ee",
    tertiary_color: "#020617",
  },
  {
    id: "luxury_builder",
    name: "Luxury Builder",
    description: "Custom homes, architecture, interiors, premium services.",
    industry_architecture: "service",
    color_theme: "luxury",
    layout_preset: "magazine",
    primary_color: "#111111",
    secondary_color: "#d6a84f",
    tertiary_color: "#f6efe5",
  },
  {
    id: "medical_clean",
    name: "Medical Clean",
    description: "Clinics, wellness, dental, therapy, patient services.",
    industry_architecture: "medical",
    color_theme: "light",
    layout_preset: "card_block",
    primary_color: "#0f766e",
    secondary_color: "#5eead4",
    tertiary_color: "#f0fdfa",
  },
  {
    id: "nonprofit_community",
    name: "Nonprofit Community",
    description: "Churches, nonprofits, community groups, missions.",
    industry_architecture: "nonprofit",
    color_theme: "modern",
    layout_preset: "featured_media",
    primary_color: "#365314",
    secondary_color: "#84cc16",
    tertiary_color: "#f7fee7",
  },
];

export type DesignKit = (typeof designKits)[number];